/**
 * Commercial Plugin Registry
 *
 * This is the central extension point for commercial BridgeLink plugins.
 * It defines the interfaces that plugins register into at app startup and the
 * mutable registry that the base app reads from at render time.
 *
 * ── How it works ───────────────────────────────────────────────────
 *
 *  1. Base app imports `@/plugins` as a side effect (in login/layout and in
 *     each generic core route file under app/).
 *  2. `plugins/index.ts` (generated by scripts/generate-plugin-index.mjs)
 *     imports each plugin module on disk and passes it to
 *     `registerPluginModule()` from `lib/plugin-manifest.ts`, then calls
 *     `_markPluginsReady()` from `plugins/_ready.ts`.
 *  3. Each plugin's index module default-exports a `definePlugin({...})`
 *     manifest; `registerPlugin()` fans its contributions out into this
 *     registry (and the channel-scoped registries) via the register*()
 *     functions below, which are now the internal implementation.
 *  4. Base app components await `pluginsReady` and then read from
 *     `pluginRegistry` (and single-fill mount points via `lib/plugin-slots`).
 *
 * In the base (open-source) build, no plugin directories exist, so the
 * generated `plugins/index.ts` is empty and the base app gracefully handles
 * all null/empty states. Commercial builds add the plugin directories and the
 * generator picks them up automatically.
 *
 * ── Stability contract (read before changing this file) ───────────────────────
 *
 * The contribution interfaces in this file (and the manifest type in
 * `lib/plugin-manifest.ts` that references them) are a STABLE WIRE CONTRACT.
 * Plugins ship as independently-built artifacts (today via the commercial
 * repo's checkout, future via runtime loading) and bind to whatever shape the
 * running core exposes. Backward-incompatible changes (renames, removed
 * fields, narrowed types) require a versioned migration and must not be done
 * casually. Adding new optional fields is safe. New single-fill plugin mount
 * points go in `lib/plugin-slots.ts` — do NOT add per-plugin fields here.
 *
 * ── Connector plugins ─────────────────────────────────────────────────────────
 *
 * Source and destination connector plugins (e.g. SSL Settings) use a separate
 * mutable registry to avoid importing app/ types from lib/. See:
 *   app/(app)/channels/_connectors/plugins/index.ts         (source)
 *   app/(app)/channels/_connectors/destinations/plugins/index.ts  (destination)
 */

import type { ComponentType } from "react";
import type { LucideIcon } from "lucide-react";
import type { NextRequest } from "next/server";
import type { RefItem } from "@/lib/reference-data";
import type * as MonacoType from "monaco-editor";

// ── Monaco editor action plugin type ──────────────────────────────────────────

/**
 * A Monaco editor action contributed by a plugin.
 *
 * Mounted on Monaco editor instances inside JavaScriptPanel via
 * `editor.addAction()`. The `run` callback is invoked at action-call time —
 * read `monacoRef.current` inside the body.
 *
 * Field semantics mirror Monaco's `IActionDescriptor`.
 */
export interface MonacoEditorAction {
  /** Unique action id — must be globally unique across all registered actions */
  id: string;
  /** Label shown in the right-click context menu */
  label: string;
  /** Optional Monaco keybindings (use `monaco.KeyMod` and `monaco.KeyCode` constants) */
  keybindings?: number[];
  /** Optional context menu group id (e.g. "ai") used to group related actions */
  contextMenuGroupId?: string;
  /** Optional sort order within the context menu group */
  contextMenuOrder?: number;
  /** Invoked when the user triggers the action — receives the editor and Monaco namespace */
  run: (editor: MonacoType.editor.IStandaloneCodeEditor, monaco: typeof MonacoType) => void;
  /**
   * Server plugin name (must match `GET /extensions/plugins/`) used for
   * server-enablement gating. When set, the action is not mounted
   * unless that plugin is installed AND enabled on the connected server.
   * Stamped from the definition's `serverPluginName` by `registerPlugin()`.
   * Omit for client-only actions that should always appear.
   */
  pluginName?: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, this surface is hidden unless the server
   * reports it licensed (Active/Expiring Soon), in addition to any `pluginName`
   * enablement gate. Stamped from the definition's `licensedPluginId` by
   * `registerPlugin()`. Omit for core / unlicensed surfaces.
   */
  licensedPluginId?: string;
}

// ── Editor context / overlay plugin types ─────────────────────────────────────

/**
 * Context passed to plugin editor actions and overlays so the plugin knows
 * which surface is being edited (filter, transformer, code template, etc.).
 */
export interface EditorContext {
  /** Which BridgeLink editor surface this context belongs to */
  location:
    | "filter-transformer"
    | "code-template"
    | "channel-script"
    | "global-script"
    | "connector-script";
  /** Filter/transformer mode — undefined for code-template / channel-script locations */
  mode?: "filter" | "transformer" | "responseTransformer";
  /** True when the editor belongs to a source connector */
  isSource?: boolean;
  /**
   * Connector transport name (e.g. "JavaScript Writer", "Database Reader") — connector-script
   * location only. Populated from the connector's `transportName`, or a script-surface label for
   * connector-script editors that have no transport (e.g. "JavaScript Attachment Handler").
   * The AI plugin renders it as the "Connector type:" context line and maps it to a per-surface
   * script-role contract.
   */
  connectorType?: string;
  /** Inbound data type (e.g. "HL7V2"), filter/transformer location only */
  inboundDataType?: string;
  /** Outbound data type, filter/transformer location only */
  outboundDataType?: string;
  /** Inbound message template content (truncated by caller if needed) */
  inboundTemplate?: string | null;
  /** Outbound message template content */
  outboundTemplate?: string | null;
  /** Channel id (filter/transformer / channel-script locations) */
  channelId?: string;
  /** Channel name */
  channelName?: string;
  /** Code template name (code-template location only) */
  templateName?: string;
  /** Code template type — e.g. FUNCTION, DRAG_AND_DROP_CODE, COMPILED_CODE */
  templateType?: string;
  /** Code template context types — e.g. ["SOURCE_FILTER_TRANSFORMER"] */
  contextTypes?: string[];
}

/**
 * Props passed to a plugin-registered editor overlay component.
 *
 * The overlay renders inside the editor container and is given live refs to
 * the Monaco editor and namespace so it can read selection/cursor and apply
 * edits. The refs may be null until Monaco mounts — guard with `?.current`.
 */
export interface EditorOverlayProps {
  /** Live ref to the Monaco editor instance — null until handleMount fires */
  editorRef: React.RefObject<MonacoType.editor.IStandaloneCodeEditor | null>;
  /** Live ref to the Monaco namespace — null until handleBeforeMount fires */
  monacoRef: React.RefObject<typeof MonacoType | null>;
  /** Editor context describing the surface being edited */
  context: EditorContext;
}

// ── Reference panel tab plugin types ──────────────────────────────────────────

/**
 * Props passed to a plugin-registered Reference Panel tab component.
 */
export interface ReferencePanelTabProps {
  /** Editor context — undefined while context is unavailable */
  context?: EditorContext;
}

/**
 * Describes a plugin-contributed tab in the filter/transformer Reference Panel.
 *
 * Tabs render after the built-in Reference / Message Trees / Message Templates
 * tabs. Plugins call `registerReferencePanelTab()` at startup; the panel reads
 * `pluginRegistry.referencePanelTabs` at render time.
 */
export interface ReferencePanelTabPlugin {
  /** Unique tab key — must not collide with "reference" / "trees" / "templates" */
  key: string;
  /** Label shown in the tab bar */
  label: string;
  /** Component rendered in the tab content area */
  component: ComponentType<ReferencePanelTabProps>;
  /**
   * Server plugin name (must match `GET /extensions/plugins/`) used for
   * server-enablement gating. When set, the tab is hidden unless
   * that plugin is installed AND enabled on the connected server. Stamped from
   * the definition's `serverPluginName` by `registerPlugin()`. Omit for
   * client-only tabs that should always appear.
   */
  pluginName?: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, this surface is hidden unless the server
   * reports it licensed (Active/Expiring Soon), in addition to any `pluginName`
   * enablement gate. Stamped from the definition's `licensedPluginId` by
   * `registerPlugin()`. Omit for core / unlicensed surfaces.
   */
  licensedPluginId?: string;
}

/**
 * Describes a plugin-contributed category in the built-in "Reference" tab of the
 * filter/transformer Reference Panel.
 *
 * Mirrors Java's `CodeTemplatePlugin.getReferenceItems()` extension point (see
 * the SSL plugin's `SSLManagerReferencePlugin`), which contributes a named
 * category of reference items that BridgeLink's `ReferenceListFactory` merges
 * into both the Reference panel and the JavaScript autocomplete cache.
 *
 * Plugins call `registerReferenceCategory()` at startup. The category is read at
 * render time by the Reference panel (`reference-list.tsx`) and by the Monaco
 * completion provider (`monaco-rhino.ts`). Categories appear after the built-in
 * categories (matching Java's ordering of non-enum categories).
 */
export interface ReferenceCategoryPlugin {
  /** Unique category id — must not collide with built-in CATEGORIES ids. */
  id: string;
  /** Category label shown in the "Category:" dropdown. */
  label: string;
  /**
   * Reference items in this category. For drag-and-drop parity with Java's
   * `DRAG_AND_DROP_CODE` templates, set each item's `code` to the snippet that
   * should be inserted verbatim. Set `contexts` to restrict autocomplete to
   * specific editor contexts (e.g. the connector context set).
   */
  items: RefItem[];
  /**
   * Server plugin name (must match `GET /extensions/plugins/`, e.g. "SSL
   * Settings") used for server-enablement gating. When set, the category is
   * hidden unless that plugin is installed AND enabled on the connected server.
   * Omit for client-only categories that should always appear.
   */
  pluginName?: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, this surface is hidden unless the server
   * reports it licensed (Active/Expiring Soon), in addition to any `pluginName`
   * enablement gate. Stamped from the definition's `licensedPluginId` by
   * `registerPlugin()`. Omit for core / unlicensed surfaces.
   */
  licensedPluginId?: string;
}

// ── Channel editor tab plugin type ────────────────────────────────────────────

/**
 * Describes a plugin-contributed tab in the Channel Editor.
 *
 * Mirrors Java's ChannelTabPlugin — plugins contribute tabs that appear after
 * the built-in Summary / Source / Destinations / Scripts tabs.
 * Only shown when editing an existing channel (not on the "new channel" form).
 */
export interface ChannelEditorTabPlugin {
  /** Unique key — used as the tab value; must not collide with built-in EditorTab values */
  key: string;
  /** Label shown in the tab bar */
  label: string;
  /** Component rendered in the tab content area */
  component: ComponentType<{ channelId: string; channelName: string }>;
  /**
   * Server plugin name (must match `GET /extensions/plugins/`, e.g. "Version
   * History Plugin") used for server-enablement gating. When set, the tab is
   * hidden unless that plugin is installed AND enabled on the connected server.
   * Omit for client-only tabs that should always appear.
   */
  pluginName?: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, this surface is hidden unless the server
   * reports it licensed (Active/Expiring Soon), in addition to any `pluginName`
   * enablement gate. Stamped from the definition's `licensedPluginId` by
   * `registerPlugin()`. Omit for core / unlicensed surfaces.
   */
  licensedPluginId?: string;
}

// ── Re-exported types ──────────────────────────────────────────────────────────

/**
 * Permission level for RBAC gating.
 * Previously defined in lib/hooks/use-permissions.ts — lives here to avoid
 * circular imports between the hook and the RBAC plugin's permissions provider.
 */
export type PermissionLevel = "No Permission" | "View" | "Editor";

// ── Page plugin type ──────────────────────────────────────────────────────────

/**
 * Describes a plugin-contributed full page accessible via /p/{slug}.
 *
 * The page is rendered by the catch-all route app/(app)/p/[slug]/page.tsx.
 * Plugins call registerPage() at startup; the sidebar reads pluginRegistry.pages
 * to inject nav items dynamically.
 */
export interface PagePlugin {
  /** URL slug — page is served at /p/{slug} */
  slug: string;
  /** Sidebar label */
  label: string;
  /** Sidebar icon (lucide-react icon component) */
  icon: LucideIcon;
  /** Sidebar tooltip text */
  tooltip: string;
  /**
   * Which nav group to insert into: "Operations", "Build", or "Administration".
   * Defaults to "Operations" if omitted.
   */
  navGroup?: "Operations" | "Build" | "Administration";
  /** The React component rendered at /p/{slug} */
  component: ComponentType;
  /** RBAC permission key — item hidden when "No Permission". Omit to always show. */
  permissionKey?: string | string[];
  /**
   * Server plugin name (must match `GET /extensions/plugins/`, e.g. "Version
   * History Plugin") used for server-enablement gating. When set, the nav item
   * and the /p/{slug} route are hidden unless that plugin is installed AND
   * enabled on the connected server. Omit for client-only pages that should
   * always appear.
   */
  pluginName?: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, the nav item and the /p/{slug} route are
   * hidden unless the server reports it licensed (Active/Expiring Soon), in
   * addition to any `pluginName` enablement gate. Stamped from the definition's
   * `licensedPluginId` by `registerPlugin()`. Omit for core / unlicensed pages.
   */
  licensedPluginId?: string;
  /**
   * When "drawer": clicking the sidebar item opens a slide-out drawer instead of navigating.
   * The /p/{slug} route still exists as a fallback for direct URL access.
   * Defaults to "page".
   */
  openAs?: "page" | "drawer";
  /** Drawer width in px. Only used when openAs is "drawer". Defaults to 480. */
  drawerWidth?: number;
}

// ── Settings plugin tab type ───────────────────────────────────────────────────

/**
 * Props that plugin settings tab components may accept for toolbar integration.
 *
 * `actionsRef` is intentionally typed `any` — see. It is part of the
 * stable cross-repo plugin wire contract and must accept both the typed
 * (oidc/ssl declare `MutableRefObject<XxxTabActions>`) and loose
 * (access-control/anchor/siem/license-manager use this shape directly) plugin
 * tab camps. Because `MutableRefObject<T>` is checked contravariantly, `any` is
 * the only type that keeps both camps assignable. Narrowing it requires making
 * this contract generic and editing the commercial overlay; deferred post-GA.
 */
export interface PluginTabProps {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any --: stable cross-repo wire contract; `any` is the only type that keeps both the typed (oidc/ssl) and loose (access-control/anchor/siem/license-manager) plugin-tab camps assignable under contravariant ref checks. Structural fix needs a generic contract + commercial overlay edits; deferred post-GA.
  actionsRef?: React.MutableRefObject<any>;
  onActionsChanged?: () => void;
  /**
   * Reports the tab's unsaved-changes (dirty) state up to the Settings host so
   * plugin tabs participate in the same unsaved-changes guard as built-in tabs
   * (the host tracks this in its dirtyTabs map). Mirrors Java SettingsPane, where
   * confirmLeave operates on the active panel whether built-in or plugin.
   */
  onDirty?: (isDirty: boolean) => void;
  /**
   * Optional pure-save handle the Settings host populates and calls from its
   * unsaved-changes guard / tab-switch prompt. A settings tab sets
   * `saveRef.current` to a function that validates + saves and THROWS on failure,
   * so a failed save aborts navigation (mirrors built-in tabs' saveRef and Java's
   * confirmLeave where doSave()==false keeps you on the panel). Tabs that don't
   * set it are simply never auto-saved by the guard.
   */
  saveRef?: React.MutableRefObject<() => Promise<void>>;
}

/**
 * Describes a plugin-contributed tab in the Settings page.
 *
 * Mirrors Java's SettingsPanelPlugin — plugins contribute settings tabs which
 * are shown only when the server reports the plugin as installed and enabled.
 */
export interface SettingsPluginTab {
  /** Display name shown on the tab trigger — e.g. "Certificate Manager" */
  tabLabel: string;
  /** Unique key used for the Tabs value prop — e.g. "certificate-manager" */
  tabKey: string;
  /**
   * The plugin name exactly as returned by GET /extensions/plugins/.
   * Used to look up PluginMetaData.enabled on the server.
   */
  pluginName: string;
  /**
   * License-entitlement gate. The License Manager `pluginId` string
   * for the owning plugin; when set, the tab is hidden unless the server
   * reports it licensed (Active/Expiring Soon), in addition to the `pluginName`
   * enablement gate. Stamped from the definition's `licensedPluginId` by
   * `registerPlugin()`. Omit for core / unlicensed settings tabs.
   */
  licensedPluginId?: string;
  /** The React component to render inside the tab content area. */
  component: ComponentType<PluginTabProps>;
  /**
   * The action panel component rendered in the dockable toolbar.
   *
   * Intentionally typed `ComponentType<any>` — see. Each plugin's
   * action panel declares its own required prop interface (e.g.
   * `OidcActionPanelProps`); because `ComponentType<P>` is checked
   * contravariantly, no single non-`any` slot type accepts every plugin's
   * panel. Narrowing it requires making this contract generic and editing the
   * commercial overlay; deferred post-GA.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any --: stable cross-repo wire contract; each plugin panel has its own required props, so no single non-`any` `ComponentType` slot accepts every panel under contravariant checks. Structural fix needs a generic contract + commercial overlay edits; deferred post-GA.
  actionPanel: ComponentType<any> | null;
  /** RBAC permission key — tab hidden when "No Permission". e.g. "Settings.Data Pruner" */
  permissionKey?: string;
}

// ── SSO login extension point ──────────────────────────────────────────────────

/** Props passed to the SSO login section rendered below the credentials form. */
export interface SsoLoginProps {
  /** Current server URL entered by the user. */
  serverUrl: string;
  /** True while credential login is in progress — SSO button should be disabled. */
  disabled: boolean;
  /** Called to surface an error on the login page. */
  onError: (message: string) => void;
  /** Called when SSO navigation is starting (true) or has failed/ended (false). */
  onLoadingChange: (loading: boolean) => void;
}

// ── Repo changes summary (version history extension point) ────────────────────

/**
 * Parsed summary of uncommitted working-tree changes from the version history
 * Git repo. Consumed by main pages to show per-entity "uncommitted" indicators.
 */
export interface RepoChangesSummary {
  /** Channel IDs with uncommitted changes (modified, deleted, or untracked). */
  channelIds: Set<string>;
  /** Code template IDs with uncommitted changes. */
  templateIds: Set<string>;
}

// ── Registry ───────────────────────────────────────────────────────────────────

interface PluginRegistry {
  /**
   * Full pages contributed by plugins. Rendered at /p/{slug}.
   * Sidebar reads this to inject nav items dynamically.
   */
  pages: PagePlugin[];

  /**
   * Settings tabs contributed by commercial plugins.
   * Rendered in Settings page alongside built-in tabs (Data Pruner, etc.).
   */
  settingsTabs: SettingsPluginTab[];

  /**
   * SSO login section rendered below the credentials form on the login page.
   * Null when no SSO plugin is installed.
   */
  ssoLoginSection: ComponentType<SsoLoginProps> | null;

  /**
   * Called after successful credential login. Plugins can throw to block login
   * (e.g. RBAC/OIDC exclusive mode enforcement). Null when not registered.
   */
  postLoginVerify: ((serverUrl: string, username: string) => Promise<void>) | null;

  /**
   * Loads RBAC permissions for the current user. Returns null to indicate
   * allow-all (plugin not installed or user has no role). Null when not registered.
   */
  permissionsProvider: (() => Promise<Map<string, PermissionLevel> | null>) | null;

  /**
   * Extra tabs contributed by plugins for the Channel Editor.
   * Rendered after the built-in Summary / Source / Destinations / Scripts tabs.
   * Only shown when editing an existing channel (mode === "edit").
   */
  channelEditorTabs: ChannelEditorTabPlugin[];

  /**
   * Monaco editor actions contributed by plugins. Mounted on Monaco editor
   * instances via `editor.addAction()` in JavaScriptPanel (see
   * `mountPluginMonacoActions`, which applies server-enablement
   * gating). Empty array is the safe no-op default.
   */
  monacoEditorActions: MonacoEditorAction[];

  /**
   * Plugin-contributed tabs for the filter/transformer Reference Panel.
   * Rendered after the built-in Reference / Message Trees / Message Templates tabs.
   * Empty array is the safe no-op default.
   */
  referencePanelTabs: ReferencePanelTabPlugin[];

  /**
   * Plugin-contributed categories for the built-in "Reference" tab of the
   * filter/transformer Reference Panel. Rendered after the built-in categories
   * and surfaced in JavaScript autocomplete. Empty array is the safe no-op default.
   */
  referenceCategories: ReferenceCategoryPlugin[];

  /**
   * Pages registered against fixed core route paths.
   * Each entry has the App Router path the core route file looks up
   * (e.g. "/auth/callback") and the component to render. The route file
   * renders the matching component, or 404s if absent.
   *
   * Plugins call `registerRoutePage(path, component)` at startup. Last-wins
   * if the same path is registered twice.
   */
  routePages: { path: string; component: ComponentType }[];

  /**
   * Server-side route handlers registered against a method+path key.
   * Key format: `"<METHOD> <path>"` (e.g. `"GET /api/oidc-discovery"`).
   * The corresponding core route file dispatches through this map and
   * returns 404 when nothing is registered.
   *
   * Plugins call `registerRouteHandler(method, path, handler)` at startup.
   * Last-wins if the same method+path is registered twice.
   */
  routeHandlers: Map<string, RouteHandler>;
}

/** Server-side route handler signature accepted by `registerRouteHandler`. */
export type RouteHandler = (req: NextRequest) => Promise<Response> | Response;

const registry: PluginRegistry = {
  pages: [],
  settingsTabs: [],
  ssoLoginSection: null,
  postLoginVerify: null,
  permissionsProvider: null,
  channelEditorTabs: [],
  monacoEditorActions: [],
  referencePanelTabs: [],
  referenceCategories: [],
  routePages: [],
  routeHandlers: new Map(),
};

/** Read-only view of the plugin registry for base app components. */
export const pluginRegistry: Readonly<PluginRegistry> = registry;

// ── Registration helpers (called by plugins at startup) ───────────────────────

/** Register a full page contributed by a plugin. Accessible at /p/{slug}. */
export function registerPage(page: PagePlugin): void {
  if (registry.pages.some((p) => p.slug === page.slug)) return;
  registry.pages.push(page);
}

/** Register a settings tab contributed by a plugin. */
export function registerSettingsTab(tab: SettingsPluginTab): void {
  if (registry.settingsTabs.some((t) => t.tabKey === tab.tabKey)) return;
  registry.settingsTabs.push(tab);
}

/**
 * Register the SSO login section and post-login verification hook.
 *
 * @param section     Component rendered below the credentials form.
 * @param postVerify  Called after credential login; throw to block with a message.
 */
export function registerSsoLogin(
  section: ComponentType<SsoLoginProps>,
  postVerify: (serverUrl: string, username: string) => Promise<void>
): void {
  registry.ssoLoginSection = section;
  registry.postLoginVerify = postVerify;
}

/**
 * Register an RBAC permissions provider.
 *
 * The provider is called by usePermissions() to resolve the current user's
 * permission map. Return null to indicate allow-all.
 */
export function registerPermissionsProvider(
  provider: () => Promise<Map<string, PermissionLevel> | null>
): void {
  registry.permissionsProvider = provider;
}

/**
 * Register a plugin-contributed tab for the Channel Editor.
 * The tab appears after the built-in tabs (Summary, Source, Destinations, Scripts).
 * Only rendered when editing an existing channel.
 */
export function registerChannelEditorTab(tab: ChannelEditorTabPlugin): void {
  if (registry.channelEditorTabs.some((t) => t.key === tab.key)) return;
  registry.channelEditorTabs.push(tab);
}

/**
 * Register Monaco editor actions contributed by a plugin.
 * Mounted on each Monaco editor instance via `editor.addAction()`.
 *
 * Idempotent: actions whose `id` is already present in the registry are
 * silently skipped, so the function is safe to call more than once (e.g.
 * when the plugin module is evaluated multiple times under HMR or React
 * StrictMode double-invocation).
 */
export function registerMonacoEditorActions(actions: MonacoEditorAction[]): void {
  for (const action of actions) {
    if (!registry.monacoEditorActions.some((a) => a.id === action.id)) {
      registry.monacoEditorActions.push(action);
    }
  }
}

/**
 * Register a single tab for the filter/transformer Reference Panel.
 * The tab appears after the built-in Reference / Message Trees / Message Templates tabs.
 */
export function registerReferencePanelTab(tab: ReferencePanelTabPlugin): void {
  if (registry.referencePanelTabs.some((t) => t.key === tab.key)) return;
  registry.referencePanelTabs.push(tab);
}

/**
 * Register a category of reference items for the built-in "Reference" tab of the
 * filter/transformer Reference Panel. The category appears after the built-in
 * categories and its items are surfaced in JavaScript autocomplete.
 *
 * Mirrors Java's `CodeTemplatePlugin.getReferenceItems()`. Idempotent by `id`.
 */
export function registerReferenceCategory(category: ReferenceCategoryPlugin): void {
  if (registry.referenceCategories.some((c) => c.id === category.id)) return;
  registry.referenceCategories.push(category);
}

/**
 * Register a page component for a fixed core App Router path.
 *
 * The matching core route file (e.g. `app/auth/callback/page.tsx`) renders
 * the registered component, or 404s if no plugin has registered one. The
 * route file determines the URL surface; this function determines what gets
 * rendered there.
 */
export function registerRoutePage(path: string, component: ComponentType): void {
  const existing = registry.routePages.findIndex((p) => p.path === path);
  if (existing >= 0) registry.routePages[existing] = { path, component };
  else registry.routePages.push({ path, component });
}

/**
 * Register a server-side route handler for a fixed core App Router path.
 *
 * The matching core route file dispatches `<METHOD> <path>` through the
 * registry and returns 404 when no plugin has registered a handler. Plugins
 * provide an implementation that conforms to Next's `(req: NextRequest) =>
 * Response | Promise<Response>` signature.
 */
export function registerRouteHandler(
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH",
  path: string,
  handler: RouteHandler
): void {
  registry.routeHandlers.set(`${method} ${path}`, handler);
}

/**
 * Register a server-side route handler whose module is loaded lazily, on first
 * request, via the supplied `loader` (a `() => import("./handler").then((m) => m.POST)`
 * thunk).
 *
 * Registration is synchronous — the dispatch wrapper is stored immediately, so the
 * core route's `routeHandlers.get()` (after `pluginsReady`) always finds it, with no
 * race. But the handler MODULE and its server-only dependencies (SDKs, Node-core
 * polyfills such as `crypto`/`stream` whose browserify shims call the `Function()`
 * constructor at module init) are imported only when the route actually runs,
 * server-side. Plugin `index.ts` files are imported by the client app shell too
 * (`import "@/plugins"`), so a static handler import drags those modules into the
 * client bundle's page-load graph, where the eval-class init calls trip the app CSP
 * (`script-src 'self'`). Use this for any plugin route handler that imports an SDK,
 * a Node core module, or other server-only/heavy dependencies. See.
 */
export function registerRouteHandlerLazy(
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH",
  path: string,
  loader: () => Promise<RouteHandler>
): void {
  let loaded: Promise<RouteHandler> | null = null;
  registry.routeHandlers.set(`${method} ${path}`, (req) => {
    // On a failed import, clear the cache so the next request retries instead of
    // replaying a permanently-rejected promise review).
    loaded ??= loader().catch((err) => {
      loaded = null;
      throw err;
    });
    return loaded.then((handler) => handler(req));
  });
}
