"use client";

import { useState } from "react";
import { useCompactMode } from "@/lib/hooks/use-compact-mode";
import { HoverTooltip } from "@/components/hover-tooltip";
import { ArrowDownToLine, CheckCircle2, Download, Filter, Shuffle, Upload } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SettingsSection, FieldRow, SummaryChip } from "@/components/settings/settings-section";
import { SETTINGS_TAB_MIN_WIDTH } from "@/components/settings/settings-tab-scroll";
import type { SourceConnectorState, MessageStorageMode } from "../_lib/channel-xml";
import {
  resolveXmlVersion,
  withVersion,
  parseSharedSourceSettings,
  resolveDefaultQueueBufferSize,
} from "../_lib/channel-xml";
import {
  buildResponseOptions,
  QUEUE_ON_RESPONSES,
  type DestinationRef,
} from "../_lib/source-response-options";
import { CONNECTOR_REGISTRY, visibleSourceConnectorTypes } from "../_connectors";
import { PLUGIN_REGISTRY } from "../_connectors/plugins";
import type { ValidationError } from "../_connectors/shared/validate-utils";
import { validateListenerSettings } from "../_connectors/shared/validate-utils";
import { usePluginSurfaceEnabled } from "@/lib/plugin-gating";
import { inputCls, selectCls } from "../_connectors/shared/styles";
import { RadioGroup } from "../_connectors/shared/radio-group";
import { CommittedNumberInput } from "../_connectors/shared/committed-number-input";

// ─── Source-queue storage-mode warning (mirrors SourceSettingsPanel.updateQueueWarning) ──
//
// Java shows the warning when source queue is ON and storage mode is METADATA or
// DISABLED — note this set does NOT include RAW (unlike the destination-tab rule).
const SOURCE_QUEUE_WARN_STORAGE_MODES = new Set<MessageStorageMode>(["METADATA", "DISABLED"]);

// Per-field help text. Ported verbatim from Java SourceSettingsPanel (HTML/<br/>
// flattened to plain strings); shown on hover over each control.
const TIP = {
  sourceQueue:
    "Selecting OFF will process the message before sending the response (can use response from destinations). Selecting ON will queue messages and immediately send a response (cannot use response from destinations).",
  queueBufferSize:
    "The buffer size for the source queue. Up to this many connector messages may be held in memory at once when queuing.",
  response:
    'Select a destination\'s response, the postprocessor return value, or a response map variable. Select "Auto-generate" to send a response generated by the inbound data type using the raw message: Before processing (SENT status); After source transformer (source status); Destinations completed (status based on destination statuses, precedence ERROR, QUEUED, SENT, FILTERED).',
  processBatch:
    "Select Yes to enable batch processing. Batch messages are only supported if the source connector's inbound properties contains a Batch section.",
  batchResponse:
    "Each message in the batch contains its own response that is generated via the method selected above. Select either the response from the first or last message in the batch to be sent back to the originating system.",
  maxProcessingThreads:
    "The maximum number of messages that can process through the channel simultaneously. Note that when this value is greater than 1, message order is NOT guaranteed.",
} as const;

// ─── Props ────────────────────────────────────────────────────────────────────

interface SourceTabProps {
  sourceConnector: SourceConnectorState;
  /**
   * Destination connectors (metaDataId + name) for the Response dropdown. The
   * persisted value is `d<metaDataId>`; the label shown is the connector name.
   */
  destinations: DestinationRef[];
  /** Response-map variables harvested from filters/transformers/scripts (Response dropdown). */
  responseVars: string[];
  /** Channel message storage mode — gates the source-queue storage-mode warning. */
  messageStorageMode?: MessageStorageMode;
  onChange: (updates: Partial<SourceConnectorState>) => void;
  isDark: boolean;
  /** Forwarded to connector sections that make server-side API calls (e.g. DB metadata). */
  channelId?: string;
  channelName?: string;
  onOpenFilter?: () => void;
  onOpenTransformer?: () => void;
  /** Export this source connector to an XML file. */
  onExport?: () => void;
  /** Replace this source connector from an imported XML file. */
  onImport?: () => void;
  /** Field names that failed save-time validation — merged with locally-validated fields. */
  externalInvalidFields?: Set<string>;
  /** Called when the user edits any field — clears save-time highlights from the parent. */
  onClearExternalErrors?: () => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Compare two XML strings ignoring insignificant whitespace between tags. */
function xmlEffectivelyEqual(a: string | null, b: string | null): boolean {
  if (a === b) return true;
  if (!a || !b) return false;
  const norm = (s: string) =>
    s
      .replace(/>\s+</g, "><")
      .replace(/\s+version="[^"]*"/g, "")
      .replace(/<queueBufferSize>\d+<\/queueBufferSize>/g, "")
      .trim();
  return norm(a) === norm(b);
}

/** Count top-level elements inside <elements> of a filter or transformer XML string. */
function countXmlElements(xml: string | null | undefined): number {
  if (!xml) return 0;
  try {
    const doc = new DOMParser().parseFromString(xml, "application/xml");
    return doc.querySelector("elements")?.children.length ?? 0;
  } catch {
    return 0;
  }
}

// ─── Fallback for connectors without a registered definition ──────────────────

function UnimplementedBottomSection({ transportName }: { transportName: string }) {
  return (
    <SettingsSection title={`${transportName} Settings`}>
      <p className="text-sm text-gray-500 dark:text-gray-400 italic">
        Settings for <span className="font-medium not-italic">{transportName}</span> can be
        configured in the XML tab.
      </p>
    </SettingsSection>
  );
}

// ─── SourceTab ────────────────────────────────────────────────────────────────

export function SourceTab({
  sourceConnector: sc,
  destinations,
  responseVars,
  messageStorageMode,
  onChange,
  isDark,
  channelId,
  channelName,
  onOpenFilter,
  onOpenTransformer,
  onExport,
  onImport,
  externalInvalidFields,
  onClearExternalErrors,
}: SourceTabProps) {
  const { viewDensity } = useCompactMode();
  const surfaceEnabled = usePluginSurfaceEnabled();
  const connectorTypes = visibleSourceConnectorTypes(surfaceEnabled);
  const {
    transportName,
    respondAfterProcessing,
    queueBufferSize,
    responseVariable,
    processBatch,
    firstResponse,
    processingThreads,
  } = sc;

  const [pendingType, setPendingType] = useState<string | null>(null);
  const [invalidFields, setInvalidFields] = useState<Set<string>>(new Set());

  // Build the Response dropdown options (built-ins + destination d# entries +
  // harvested response-map vars + any preserved unknown saved value).
  const responseOptions = buildResponseOptions(
    respondAfterProcessing,
    destinations,
    responseVars,
    responseVariable
  );
  // Friendly label for the summary chip (destination entries show the connector name).
  const responseLabel =
    responseOptions.find((o) => o.value === responseVariable)?.label ?? responseVariable;

  // Source-queue storage-mode warning: queue ON + storage mode METADATA/DISABLED.
  const showQueueWarn =
    !respondAfterProcessing &&
    !!messageStorageMode &&
    SOURCE_QUEUE_WARN_STORAGE_MODES.has(messageStorageMode);

  const connectorDef = CONNECTOR_REGISTRY[transportName];
  const TopSection = connectorDef?.TopSection;
  const BottomSection = connectorDef?.BottomSection;

  // Wrap onChange to clear field highlights when user edits any field
  function handleChange(updates: Partial<SourceConnectorState>) {
    if (invalidFields.size > 0) setInvalidFields(new Set());
    onClearExternalErrors?.();
    onChange(updates);
  }

  // Mirrors the Java client's ConnectorTypeDecoration: a connector plugin (e.g.
  // SSL Settings) can secure the transport with TLS, which listener connectors
  // use to render an https:// URL preview. True when any applicable + enabled
  // plugin reports securesTransport() for the current properties.
  const securesTransport = PLUGIN_REGISTRY.some(
    (p) =>
      surfaceEnabled(p) &&
      p.isApplicable(transportName, sc.propertiesXml) &&
      p.securesTransport?.(sc.propertiesXml) === true
  );

  const sectionProps = {
    propertiesXml: sc.propertiesXml,
    onChange: handleChange,
    isDark,
    channelId,
    channelName,
    invalidFields: new Set([...invalidFields, ...(externalInvalidFields ?? [])]),
    transportName,
    transformerXml: sc.transformerXml,
    securesTransport,
  };

  // ── Helpers ──────────────────────────────────────────────────────────────────

  function set<K extends keyof SourceConnectorState>(key: K, val: SourceConnectorState[K]) {
    handleChange({ [key]: val } as Partial<SourceConnectorState>);
  }

  function applyTypeChange(newType: string) {
    setInvalidFields(new Set());
    const def = CONNECTOR_REGISTRY[newType];
    // Reset the shared source settings (response/queue/batch/threads) to the new type's defaults,
    // mirroring Java's ChannelSetup.changeConnectorType → sourceConnectorPanel.getDefaults()/
    // setProperties(). Without this the stale values overwrite the new type's fresh defaults on
    // serialize (e.g. TCP Listener must default responseVariable to "Auto-generate …", firstResponse
    // true). parseSharedSourceSettings("") yields the base defaults when the type has no default blob.
    // getDefaults() yields a queueBufferSize of 0, which SourceSettingsPanel.setProperties then
    // displays as the server-configured default — so use that here rather than the template's 1000.
    const updates: Partial<SourceConnectorState> = {
      transportName: newType,
      ...parseSharedSourceSettings(def?.defaultPropertiesXml ?? ""),
      queueBufferSize: resolveDefaultQueueBufferSize(),
    };
    if (def?.defaultPropertiesXml) {
      let xml = def.defaultPropertiesXml;
      for (const plugin of PLUGIN_REGISTRY) {
        if (!surfaceEnabled(plugin)) continue;
        if (plugin.injectDefaults) xml = plugin.injectDefaults(newType, xml);
      }
      // Stamp the server version into the default blob (and any plugin-injected
      // defaults) instead of shipping the {{VERSION}} placeholder to the server.
      updates.propertiesXml = withVersion(xml, resolveXmlVersion());
    }
    onChange(updates);
  }

  function handleTypeChange(newType: string) {
    if (newType === transportName) return;

    // Compare current properties against defaults for the CURRENT connector type.
    // If they differ, the user has configured settings — warn before losing them.
    const currentDef = CONNECTOR_REGISTRY[transportName];
    let currentDefault = currentDef?.defaultPropertiesXml ?? null;
    if (currentDefault) {
      for (const plugin of PLUGIN_REGISTRY) {
        if (!surfaceEnabled(plugin)) continue;
        if (plugin.injectDefaults)
          currentDefault = plugin.injectDefaults(transportName, currentDefault);
      }
    }

    if (currentDefault && !xmlEffectivelyEqual(sc.propertiesXml, currentDefault)) {
      setPendingType(newType);
      return;
    }

    applyTypeChange(newType);
  }

  function handleValidateConnector() {
    const errors: ValidationError[] = [];
    const connectorValidate = CONNECTOR_REGISTRY[transportName]?.validate;
    if (connectorValidate) errors.push(...connectorValidate(sc.propertiesXml));
    // Shared listener host/port check — runs for any socket-listener connector
    // (no-op otherwise). Mirrors Java ConnectorPanel → ListenerSettingsPanel.checkProperties.
    errors.push(...validateListenerSettings(sc.propertiesXml));
    // Also run applicable connector plugins (e.g. HTTP Authentication) so the
    // manual Validate button surfaces the same errors as the save-time check in
    // use-channel-editor.ts. Both gate on the same enablement+license surface
    // gate (here via the usePluginSurfaceEnabled predicate; the save/enable
    // paths via surfaceGateEnabledSnapshot) so a hidden plugin's config is not
    // validated in either place item 2).
    for (const plugin of PLUGIN_REGISTRY) {
      if (!surfaceEnabled(plugin)) continue;
      if (!plugin.validate) continue;
      if (!plugin.isApplicable(transportName, sc.propertiesXml)) continue;
      errors.push(...plugin.validate(sc.propertiesXml));
    }
    if (errors.length === 0) {
      setInvalidFields(new Set());
      toast.success("The connector was successfully validated.");
    } else {
      setInvalidFields(new Set(errors.map((e) => e.field)));
      toast.error("Validation failed", {
        description: errors.map((e) => e.message).join("\n"),
        duration: 8000,
      });
    }
  }

  // ── Render ───────────────────────────────────────────────────────────────────

  return (
    <div className="overflow-auto h-full">
      <div
        className={`${SETTINGS_TAB_MIN_WIDTH} ${viewDensity === "comfortable" ? "p-6 space-y-5" : viewDensity === "compact" ? "p-3 space-y-2" : "p-4 space-y-3"}`}
      >
        {/* ── Filter / Transformer / Validate buttons ────────────────────────────── */}
        <div className="flex items-center gap-2">
          {onOpenFilter &&
            (() => {
              const n = countXmlElements(sc.filterXml);
              return (
                <button
                  onClick={onOpenFilter}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border text-gray-700 dark:text-gray-300 rounded hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
                >
                  <Filter className="w-3.5 h-3.5" />
                  Edit Filter
                  {n > 0 && (
                    <span className="ml-1 text-xs text-gray-400 dark:text-gray-500">({n})</span>
                  )}
                </button>
              );
            })()}
          {onOpenTransformer &&
            (() => {
              const n = countXmlElements(sc.transformerXml);
              return (
                <button
                  onClick={onOpenTransformer}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border text-gray-700 dark:text-gray-300 rounded hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
                >
                  <Shuffle className="w-3.5 h-3.5" />
                  Edit Transformer
                  {n > 0 && (
                    <span className="ml-1 text-xs text-gray-400 dark:text-gray-500">({n})</span>
                  )}
                </button>
              );
            })()}
          <button
            onClick={handleValidateConnector}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border text-gray-700 dark:text-gray-300 rounded hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
          >
            <CheckCircle2 className="w-3.5 h-3.5" />
            Validate Connector
          </button>
          {onExport && (
            <button
              onClick={onExport}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border text-gray-700 dark:text-gray-300 rounded hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
            >
              <Download className="w-3.5 h-3.5" />
              Export Connector
            </button>
          )}
          {onImport && (
            <button
              onClick={onImport}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm border border-border text-gray-700 dark:text-gray-300 rounded hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
            >
              <Upload className="w-3.5 h-3.5" />
              Import Connector
            </button>
          )}
        </div>

        {/* ── Connector Type ────────────────────────────────────────────────────── */}
        <div className="flex items-center gap-3">
          <span className="text-sm text-gray-600 dark:text-gray-400 shrink-0 w-[140px] text-right">
            Connector Type:
          </span>
          <select
            value={transportName}
            onChange={(e) => handleTypeChange(e.target.value)}
            className={selectCls(viewDensity)}
            data-testid="source-connector-type-select"
          >
            {connectorTypes.map((t) => (
              <option key={t} value={t}>
                {t}
              </option>
            ))}
            {/* Pin the channel's current transport when it is gated off or
                unknown, so the select shows it (disabled) instead of silently
                switching to the first option on next save. */}
            {!connectorTypes.includes(transportName) && (
              <option value={transportName} disabled>
                {transportName} (unavailable)
              </option>
            )}
          </select>
        </div>

        {/* ── Top section — rendered ABOVE Source Settings (e.g. Polling Settings) */}
        {TopSection && <TopSection {...sectionProps} />}

        {/* ── Common Source Settings ───────────────────────────────────────────── */}
        <SettingsSection
          title="Source Settings"
          icon={ArrowDownToLine}
          defaultExpanded={true}
          storageKey="bl-source-settings"
          summary={
            <>
              <SummaryChip label="Queue" value={respondAfterProcessing ? "OFF" : "ON"} />
              <SummaryChip label="Response" value={responseLabel} />
              {processBatch && <SummaryChip value="Batch" />}
              <SummaryChip label="Threads" value={String(processingThreads)} />
            </>
          }
        >
          <FieldRow label="Source Queue:">
            <HoverTooltip content={TIP.sourceQueue}>
              <select
                value={respondAfterProcessing ? "off" : "on"}
                onChange={(e) => {
                  const newRespondAfter = e.target.value === "off";
                  const updates: Partial<SourceConnectorState> = {
                    respondAfterProcessing: newRespondAfter,
                  };
                  // When switching to queue ON, only QUEUE_ON_RESPONSES are valid
                  // (no destination names, no Postprocessor, etc.)
                  if (
                    !newRespondAfter &&
                    !(QUEUE_ON_RESPONSES as readonly string[]).includes(responseVariable)
                  ) {
                    updates.responseVariable = "None";
                  }
                  onChange(updates);
                }}
                className={selectCls(viewDensity)}
              >
                <option value="off">OFF (Respond after processing)</option>
                <option value="on">ON (Respond before processing)</option>
              </select>
            </HoverTooltip>
          </FieldRow>

          {showQueueWarn && (
            <FieldRow label="">
              <div className="text-xs text-amber-600 dark:text-amber-400 leading-snug max-w-sm">
                Queuing is not supported by the current message storage mode.
              </div>
            </FieldRow>
          )}

          <FieldRow label="Queue Buffer Size:">
            <HoverTooltip content={TIP.queueBufferSize}>
              <CommittedNumberInput
                min={1}
                value={queueBufferSize}
                onCommit={(n) => set("queueBufferSize", n)}
                disabled={respondAfterProcessing}
                className={`${inputCls(viewDensity)} w-28`}
              />
            </HoverTooltip>
          </FieldRow>

          <FieldRow label="Response:">
            <HoverTooltip content={TIP.response}>
              <select
                value={responseVariable}
                onChange={(e) => set("responseVariable", e.target.value)}
                className={selectCls(viewDensity)}
                data-testid="source-response-select"
              >
                {responseOptions.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            </HoverTooltip>
          </FieldRow>

          <FieldRow label="Process Batch:">
            <RadioGroup
              name="processBatch"
              value={processBatch ? "yes" : "no"}
              onChange={(v) => set("processBatch", v === "yes")}
              // Java gates this on the connector's canBatch() — e.g. DICOM Listener forbids batching
              // (SourceSettingsPanel.java:105-117; DICOMReceiverProperties.canBatch()=false).
              disabled={connectorDef?.canBatch === false}
              options={[
                { label: "Yes", value: "yes" },
                { label: "No", value: "no" },
              ]}
              title={TIP.processBatch}
            />
          </FieldRow>

          <FieldRow label="Batch Response:">
            <RadioGroup
              name="batchResponse"
              value={firstResponse ? "first" : "last"}
              onChange={(v) => set("firstResponse", v === "first")}
              disabled={!processBatch}
              options={[
                { label: "First", value: "first" },
                { label: "Last", value: "last" },
              ]}
              title={TIP.batchResponse}
            />
          </FieldRow>

          <FieldRow label="Max Processing Threads:">
            <HoverTooltip content={TIP.maxProcessingThreads}>
              <CommittedNumberInput
                min={1}
                value={processingThreads}
                onCommit={(n) => set("processingThreads", n)}
                className={`${inputCls(viewDensity)} w-24`}
              />
            </HoverTooltip>
          </FieldRow>
        </SettingsSection>

        {/* ── Plugin sections — rendered between Source Settings and BottomSection ─
            A section renders only when:
              1. its pluginName (if set) is in the server's installed+enabled set, AND
              2. its isApplicable() returns true for the current connector + XML.
            The pluginName gate prevents server-backed plugins (e.g. SSL Settings) from
            rendering on servers where the underlying plugin isn't installed, even if
            the channel XML still carries the plugin's tag from a prior server. */}
        {PLUGIN_REGISTRY.filter(
          (p) => surfaceEnabled(p) && p.isApplicable(transportName, sc.propertiesXml)
        ).map((p, i) => (
          <p.Section key={i} {...sectionProps} />
        ))}

        {/* ── Bottom section — rendered BELOW Source Settings (and any plugins) ── */}
        {BottomSection ? (
          <BottomSection {...sectionProps} />
        ) : (
          <UnimplementedBottomSection transportName={transportName} />
        )}

        {/* ── Connector type change confirmation dialog ─────────────────────── */}
        <Dialog
          open={pendingType !== null}
          onOpenChange={(o) => {
            if (!o) setPendingType(null);
          }}
        >
          <DialogContent className="sm:max-w-md" showCloseButton={false}>
            <DialogHeader>
              <DialogTitle>Change Connector Type?</DialogTitle>
              <DialogDescription>
                Are you sure you would like to change this connector type and lose all of the
                current connector data?
              </DialogDescription>
            </DialogHeader>
            <DialogFooter className="gap-2">
              <Button variant="outline" size="sm" onClick={() => setPendingType(null)}>
                No
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  if (pendingType) applyTypeChange(pendingType);
                  setPendingType(null);
                }}
              >
                Yes
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}
